### ISSUE TITLE
Create function: calorie consumption

### ISSUE THREAD

**Issue by Tetsux3** [it1ans/lf10#31]
create entity "eatenMeals":
- name
- calories
- timestamp
 
link the table with the users and add upp all the eaten meals to calculate the available calories for the given day.

provides:
- user can specify the calories of his food
-calculate needed calories per day for the User (function already exist in Service/WeightCalculationServiceInterface)
-decrease value by user input (function already exist in Service/WeightCalculationServiceInterface)

**Comment by Keidaron** [comment]
just needs to be implemented 😂
